name: Build and Push Image

on:
  push:
    branches: [ "main" ] # Mude para "master" se for o nome da sua branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # O GitHub gera isso sozinho!

      - name: Build e Push da Imagem
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # IMPORTANTE: Mude o nome abaixo para cada repositório
          # Ex: no front, use ".../frontend:latest"
          tags: ghcr.io/grigs2/frontendreact/backend:latest